version: "3.8"

services:
  booking-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - PORT=8080
    restart: unless-stopped
    container_name: booking-system

  # Optional: Add this when you want a database
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: booking_db
  #     POSTGRES_USER: booking_user
  #     POSTGRES_PASSWORD: booking_pass
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
# volumes:
#   postgres_data:
